// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_cardapio_ru.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsHarpia {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwTG9iwUAMKdU2FUS3ecB5MXf7OkR2lIg',
    appId: '1:14422911132:web:ae815779d5d66516d96559',
    messagingSenderId: '14422911132',
    projectId: 'harpia-c699b',
    authDomain: 'harpia-c699b.firebaseapp.com',
    storageBucket: 'harpia-c699b.firebasestorage.app',
    measurementId: 'G-XEEC7NKGNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa3OVRxW4KGnZUNhwB7TPL5zEMtByHFHI',
    appId: '1:14422911132:android:b9d23fd52c0ce845d96559',
    messagingSenderId: '14422911132',
    projectId: 'harpia-c699b',
    storageBucket: 'harpia-c699b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZySXBiQTei1bVZm2lhUDqep6XI3np1hA',
    appId: '1:14422911132:ios:1f5a5f5042dff87fd96559',
    messagingSenderId: '14422911132',
    projectId: 'harpia-c699b',
    storageBucket: 'harpia-c699b.firebasestorage.app',
    androidClientId: '14422911132-ac5k471uuq6ajl62ge200i20sc9j6f74.apps.googleusercontent.com',
    iosClientId: '14422911132-921ubqc5kp7vnuu5kljtv8tini44oj0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.geotrackingStandalone',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZySXBiQTei1bVZm2lhUDqep6XI3np1hA',
    appId: '1:14422911132:ios:1f5a5f5042dff87fd96559',
    messagingSenderId: '14422911132',
    projectId: 'harpia-c699b',
    storageBucket: 'harpia-c699b.firebasestorage.app',
    androidClientId: '14422911132-ac5k471uuq6ajl62ge200i20sc9j6f74.apps.googleusercontent.com',
    iosClientId: '14422911132-921ubqc5kp7vnuu5kljtv8tini44oj0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.geotrackingStandalone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwTG9iwUAMKdU2FUS3ecB5MXf7OkR2lIg',
    appId: '1:14422911132:web:31b312dc6ab73716d96559',
    messagingSenderId: '14422911132',
    projectId: 'harpia-c699b',
    authDomain: 'harpia-c699b.firebaseapp.com',
    storageBucket: 'harpia-c699b.firebasestorage.app',
    measurementId: 'G-G9DS4P9H89',
  );
}
